theme: jekyll-theme-cayman
title: SQuARE: the SPARQL Query Agent-based Reasoning Engine
sidebar:
  nav: "docs"

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"

