theme: jekyll-theme-cayman
title: The SPARQL Query Agent-based Reasoning Engine (SQuARE)
sidebar:
  nav: "docs"

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"

