theme: jekyll-theme-cayman
title: A Validation Ontology for Semantic Reasoning Engines
#sidebar:
#  nav: "docs"

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"

